version: "3.7"

services:
  appdaemon:
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: appdaemon
    image: acockburn/appdaemon:latest
    hostname: appdaemon
    ports:
      - "5050:5050"
    environment:
      HA_URL: http://localhost:8123
      TOKEN: Create_Long_Term_Token #ADD HERE
      DASH_URL: http://localhost>:5050
    volumes:
      - '/opt/docker/appdaemon:/conf'
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/ssl:/certs:ro"
    restart: "unless-stopped"
    privileged: true
    network_mode: host