services:
  octoprint:
    image: octoprint/octoprint:latest
    container_name: octoprint
    restart: unless-stopped
    ports:
      - 5000:5000
      - 5001:8080 #http://10.0.0.131:5001/?action=stream
    devices:
    #ls -la /dev/v4l/by-id/
    #ls -la /dev/serial/by-id/

    # PRINTER USB
      - /dev/serial/by-id/usb-FTDI_FT232R_USB_UART_AC00FF2O-if00-port0:/dev/ttyUSB0
    # SIO CONTROL USB
      - /dev/serial/by-id/usb-Silicon_Labs_CP2102_USB_to_UART_Bridge_Controller_0001-if00-port0:/dev/ttySIO0
    # CAMERA USB
      - /dev/v4l/by-id/usb-046d_0825_20AF85A0-video-index0:/dev/video0
    volumes:
     - ./octoprint:/octoprint
    environment:
      - ENABLE_MJPG_STREAMER=true
      - CAMERA_DEV=/dev/video0
      - MJPG_STREAMER_INPUT="-y -n -r 1280x960 -f 30
      - TZ=Europe/Madrid


  config-editor:
    image: linuxserver/code-server
    container_name: octoprint-code-server
    ports:
      - 8443:8443
    depends_on:
      - octoprint
    restart: unless-stopped
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/Madrid
    volumes:
      - ./octoprint:/octoprint

volumes:
  octoprint:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /opt/docker/octoprint